server:
  port: 8100

spring:
  application:
    name: ZuulGateway

zuul:
  routes:
    cropservice:
      url: http://localhost:8081

    adminservice:
      url: http://localhost:8094

    farmerservice:
      url: http://localhost:8084
      
    dealerservice:
      url: http://localhost:8083